(setq out (open "index.html" :direction :output))

(princ "<!DOCTYPE html>" out)
(terpri out)
(princ "<html>" out)
(terpri out)
(princ "<head>" out)
(terpri out)
(princ "<title>My Page</title>" out)
(terpri out)
(princ "<meta charset='utf-8'>" out)
(terpri out)
(princ "</head>" out)
(terpri out)
(princ "<body>" out)
(terpri out)
(princ "<h1>Соболева Ангелина Дмитриевна БИ-41</h1>" out)
(terpri out)
(princ "<p>Hello World!</p>" out)
(terpri out)
(princ "</body>" out)
(terpri out)
(princ "</html>" out)

(close out)

(print "HTML file 'index.html' created successfully!")
(print "Open it in your browser!")